namespace wDNS.Common.Models;

// Generated by Grok based on https://www.iana.org/assignments/dns-parameters/dns-parameters.txt, thank you Grok.
public enum RecordTypes : ushort
{
    /// <summary>IPv4 address</summary>
    A = 1,

    /// <summary>Name server</summary>
    NS = 2,

    /// <summary>Mail destination (obsolete)</summary>
    MD = 3,

    /// <summary>Mail forwarder (obsolete)</summary>
    MF = 4,

    /// <summary>Canonical name</summary>
    CNAME = 5,

    /// <summary>Start of Authority</summary>
    SOA = 6,

    /// <summary>Mailbox (experimental)</summary>
    MB = 7,

    /// <summary>Mail group (experimental)</summary>
    MG = 8,

    /// <summary>Mail rename (experimental)</summary>
    MR = 9,

    /// <summary>Null record</summary>
    NULL = 10,

    /// <summary>Well-known service</summary>
    WKS = 11,

    /// <summary>Pointer</summary>
    PTR = 12,

    /// <summary>Host info</summary>
    HINFO = 13,

    /// <summary>Mailbox info</summary>
    MINFO = 14,

    /// <summary>Mail exchange</summary>
    MX = 15,

    /// <summary>Text</summary>
    TXT = 16,

    /// <summary>Responsible person</summary>
    RP = 17,

    /// <summary>AFS database</summary>
    AFSDB = 18,

    /// <summary>X.25 PSDN address</summary>
    X25 = 19,

    /// <summary>ISDN address</summary>
    ISDN = 20,

    /// <summary>Route through</summary>
    RT = 21,

    /// <summary>NSAP address</summary>
    NSAP = 22,

    /// <summary>NSAP pointer</summary>
    NSAP_PTR = 23,

    /// <summary>Signature (obsoleted by RRSIG)</summary>
    SIG = 24,

    /// <summary>Key (obsoleted by DNSKEY)</summary>
    KEY = 25,

    /// <summary>X.400 pointer</summary>
    PX = 26,

    /// <summary>Geographical position</summary>
    GPOS = 27,

    /// <summary>IPv6 address</summary>
    AAAA = 28,

    /// <summary>Location</summary>
    LOC = 29,

    /// <summary>Next (obsoleted by NSEC)</summary>
    NXT = 30,

    /// <summary>Endpoint identifier</summary>
    EID = 31,

    /// <summary>Nimrod locator</summary>
    NIMLOC = 32,

    /// <summary>Service locator</summary>
    SRV = 33,

    /// <summary>ATM address</summary>
    ATMA = 34,

    /// <summary>Naming authority pointer</summary>
    NAPTR = 35,

    /// <summary>Key exchanger</summary>
    KX = 36,

    /// <summary>Certificate</summary>
    CERT = 37,

    /// <summary>IPv6 (obsolete)</summary>
    A6 = 38,

    /// <summary>Delegation name</summary>
    DNAME = 39,

    /// <summary>Sink (kitchen sink)</summary>
    SINK = 40,

    /// <summary>EDNS option</summary>
    OPT = 41,

    /// <summary>Address prefix list</summary>
    APL = 42,

    /// <summary>Delegation signer (DNSSEC)</summary>
    DS = 43,

    /// <summary>SSH key fingerprint</summary>
    SSHFP = 44,

    /// <summary>IPsec key</summary>
    IPSECKEY = 45,

    /// <summary>Resource record signature (DNSSEC)</summary>
    RRSIG = 46,

    /// <summary>Next secure (DNSSEC)</summary>
    NSEC = 47,

    /// <summary>DNS key (DNSSEC)</summary>
    DNSKEY = 48,

    /// <summary>DHCP identifier</summary>
    DHCID = 49,

    /// <summary>NSEC3 (DNSSEC)</summary>
    NSEC3 = 50,

    /// <summary>NSEC3 parameters (DNSSEC)</summary>
    NSEC3PARAM = 51,

    /// <summary>TLSA certificate</summary>
    TLSA = 52,

    /// <summary>S/MIME certificate</summary>
    SMIMEA = 53,

    /// <summary>Host identity protocol</summary>
    HIP = 55,

    /// <summary>Node information</summary>
    NINFO = 56,

    /// <summary>RKEY</summary>
    RKEY = 57,

    /// <summary>Trust anchor link</summary>
    TALINK = 58,

    /// <summary>Child DS (DNSSEC)</summary>
    CDS = 59,

    /// <summary>Child DNSKEY (DNSSEC)</summary>
    CDNSKEY = 60,

    /// <summary>OpenPGP key</summary>
    OPENPGPKEY = 61,

    /// <summary>Child-to-parent sync</summary>
    CSYNC = 62,

    /// <summary>Zone message digest</summary>
    ZONEMD = 63,

    /// <summary>Service binding</summary>
    SVCB = 64,

    /// <summary>HTTPS binding</summary>
    HTTPS = 65,

    /// <summary>EUI-48 address</summary>
    EUI48 = 108,

    /// <summary>EUI-64 address</summary>
    EUI64 = 109,

    /// <summary>Transaction key</summary>
    TKEY = 249,

    /// <summary>Transaction signature</summary>
    TSIG = 250,

    /// <summary>Incremental zone transfer</summary>
    IXFR = 251,

    /// <summary>Full zone transfer</summary>
    AXFR = 252,

    /// <summary>Mailbox-related records (MB, MG, MR)</summary>
    MAILB = 253,

    /// <summary>Mail agent (obsolete)</summary>
    MAILA = 254,

    /// <summary>All records (*)</summary>
    ANY = 255,

    /// <summary>URI</summary>
    URI = 256,

    /// <summary>Certification Authority Authorization</summary>
    CAA = 257,

    /// <summary>Application visibility/control</summary>
    AVC = 258,

    /// <summary>Digital object architecture</summary>
    DOA = 259,

    /// <summary>Trust anchor (unassigned)</summary>
    TA = 32768,

    /// <summary>DNSSEC lookaside validation (historic)</summary>
    DLV = 32769
}
